Bringing back VOLP for ghost cell (TUM)
kmturbulenz/mglet-base pull request #124
Opened 2024-11-24 14:29 UTC by swenczowski

**--- please, consider this PR a draft for discussion, improvements to follow, not tested ---**

Dear all,

as encountered by @javierebb, mglet-base does not provide the field "VOLP", which provides the volume of intersected cells within the ghost cell immersed boundary framework. 

This PR outlines an idea to recover this field, which is primarily used for postprocessing on our side. The following considerations have been made, such that I am slightly optimistic that all relevant locations in the code have been touched. As discussed beforehand, both areas and volume are given absolute in [L^2] or [L^3] and not in terms of fractions.

![image](https://github.com/user-attachments/assets/a12a2681-bf50-4746-a0d8-9e24b22ff662)

I would much appreciate your ideas and feedback on this very rough first draft.

Best regards,

Simon

2024-11-25 08:46 UTC, hakostra requested changes
The significant comments are on some suggestions on how to improve the volp-computations.

A last small request:
Can you simultaneously rename the fields `AU`, `AV`, `AW` - that are now real areas with unit length squared - to `AREAU`, `AREAV`, `AREAW`? This will apply to the fields that are created in gc_mod.F90 and accessed in gc_flowstencils_mod.F90 - **not** gc_blockbp_mod.F90 - this should be left untouched!

This establish the practice that field `AU` = non-dimensional field with fraction of open face area - only existing locally in blocking and `AREAU` = real, physical area with unit length squared used during time-integration.

It is enough to rename the fields them selves, you do not need to rename the pointer arrays unless you see particular needs, i.e. change:

```
CALL set_field("AU")
CALL get_fieldptr(au, "AU")
```
to
```
CALL set_field("AREAU", istag=1, units=[0, 2, 0, 0, 0, 0, 0])
CALL get_fieldptr(au, "AREAU")
```
I think you get this point as well.

2024-11-25 09:29 UTC, swenczowski commented on src/ib/gc_stencils_mod.F90
> +                            + areax * (swx - xstag)
Sorry, that also came to my mind yesterday evening -- of course, the difference between two staggered positions is the pressure cell side length...

When coding it, I was too focussed on a pure replication of the previous implementation... Will be changed.

2024-11-25 09:29 UTC, swenczowski commented on src/ib/gc_stencils_mod.F90
> +                        areaz = aw(k-1, j, i) - aw(k, j, i)
Ok. Will be changed.

2024-11-25 09:30 UTC, swenczowski commented on src/ib/gc_stencils_mod.F90
> +        REAL(realk), INTENT(in) :: x(ii), y(jj), z(kk)
Ohh, ok. Will be changed.

2024-11-25 10:12 UTC, swenczowski commented on src/ib/gc_stencils_mod.F90
>      END SUBROUTINE get_auavaw
Ok, can be done. Admittedly, I do not dislike the current form, as it shows the systematics more clearly. However, I have no strong preferences...

2024-11-25 10:14 UTC, hakostra commented on src/ib/gc_stencils_mod.F90
>      END SUBROUTINE get_auavaw
The you make a call - I will accept both.

2024-12-01 18:36 UTC, swenczowski commented
Dear all,

this PR has been updated based on the preceding discussion. Thank you for the hints!

@hakostra, please, let me know if all points have been addressed.

@javierebb, please, already give the implementation a try.

Best regards,

Simon

2024-12-02 07:07 UTC, hakostra commented
Hi Simon, now try `ci/lint-fortran.py --fixall`

2024-12-02 11:17 UTC, swenczowski commented
> @swenczowski This looks good. Are your intentions now to apply the areau/v/w and volp to the scalar solver as discussed?

Yes, that will come now. Also, we are planning to add a volume source for the scalar field, which would also need the VOLP field.

2024-12-02 12:42 UTC, swenczowski commented
If you agree, I suggest merging the content of this PR before we continue with the actual "usage" of VOLP for the scalar.
Would that be OK for you?

2024-12-02 12:44 UTC, hakostra approved these changes

2024-12-02 12:44 UTC, merged